/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <stdio.h>
#include <MLog.h>
#include "StreamEngine.h"
/* Header for class com_example_erfan_MainActivity */

#define LOG_TAG "erfan_syd"
StreamEngine *engine;

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_example_erfan_MainActivity_initEF
        (JNIEnv *env, jobject obj) {
    if (engine == nullptr) {
        engine = new StreamEngine();
    }
}

JNIEXPORT void JNICALL Java_com_example_erfan_MainActivity_startEF
        (JNIEnv *env, jobject obj) {
    engine->start();
}

JNIEXPORT void JNICALL Java_com_example_erfan_MainActivity_stopEF
        (JNIEnv *env, jobject obj) {
    engine->stop();
}

#ifdef __cplusplus
}
#endif